# Generated by Django 4.2 on 2023-04-16 06:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0006_alter_repairer_city_id_alter_repairer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_site.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_street_app',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='text_order',
            field=models.CharField(max_length=1500, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='app_site.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография:'),
        ),
    ]
