# Generated by Django 4.2 on 2023-05-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0009_remove_orderlist_address_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='address_area',
            field=models.CharField(choices=[('DB', 'Дидубе'), ('KR', 'Крцаниси'), ('ND', 'Надзаладеви'), ('GR', 'Грмагеле'), ('ZG', 'Згвис'), ('GL', 'Глдани'), ('DI', 'Дигоми'), ('DD', 'Диди Дигоми'), ('IS', 'Исани'), ('SM', 'Самгори')], default='', max_length=3, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='address_num',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_city',
            field=models.CharField(choices=[('TB', 'Тбилиси'), ('BT', 'Батуми'), ('RS', 'Рустави')], default='TB', max_length=2, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_street_app',
            field=models.CharField(max_length=150, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='customer_feedback',
            field=models.CharField(max_length=2500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость работ'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='repairer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.repairerlist', verbose_name='Мастер'),
        ),
    ]
