# Generated by Django 4.2 on 2023-05-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0016_alter_orderlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(blank=True, null=True, verbose_name='Дата счета')),
                ('quantity_type', models.CharField(blank=True, choices=[('SV', 'Услуга'), ('ME', 'Метр'), ('QL', 'Килограмм'), ('TH', 'Штука')], max_length=3, null=True, verbose_name='Измерение')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.orderlist')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Услуга')),
                ('type', models.CharField(blank=True, choices=[('EL', 'Электрика'), ('PL', 'Сантехника'), ('SP', 'Кондиционирование'), ('FT', 'Ремонт/сборка мебели'), ('OT', 'Ремонт окон, дверей')], max_length=3, null=True, verbose_name='Вид работ')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderCategory',
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_site.service'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, through='app_site.Invoice', to='app_site.service'),
        ),
    ]
