# Generated by Django 4.2 on 2023-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0018_alter_invoice_date_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_in',
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='services',
            field=models.ManyToManyField(through='app_site.Invoice', to='app_site.service'),
        ),
    ]
