# Generated by Django 4.2 on 2023-09-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0030_alter_repairerlist_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Список работ заказа', 'verbose_name_plural': 'Список работ заказа'},
        ),
        migrations.AlterModelOptions(
            name='orderlist',
            options={'verbose_name': 'Список заказов', 'verbose_name_plural': 'Список заказов'},
        ),
        migrations.AlterModelOptions(
            name='repairerlist',
            options={'verbose_name': 'Мастера', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Виды работ', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AddField(
            model_name='orderlist',
            name='customer_telegram',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_status',
            field=models.CharField(blank=True, choices=[('BEG', 'Заявка получена'), ('SND', 'Направлена мастеру'), ('RCV', 'Мастеру принял заявку'), ('WRK', 'Заявка в работе'), ('END', 'Заявка выполнена')], default='BEG', max_length=3, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[('EL', 'Электрика'), ('PL', 'Сантехника'), ('SP', 'Кондиционирование'), ('FT', 'Ремонт/сборка мебели'), ('OT', 'Ремонт окон, дверей'), ('ID', 'Монтаж техники'), ('BL', 'Строительные работы'), ('CL', 'Клининг')], max_length=3, null=True, verbose_name='Вид работ'),
        ),
    ]
