# Generated by Django 4.2 on 2023-11-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0036_streertbilisi_alter_orderlist_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streertbilisi',
            options={'verbose_name': 'Улицы Тбилиси', 'verbose_name_plural': 'Улицы тбилиси'},
        ),
    ]
