# Generated by Django 4.2 on 2024-03-30 06:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_site', '0039_repairer_alter_orderlist_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Work`s list of the order', 'verbose_name_plural': 'Work`s list of the order'},
        ),
        migrations.AlterModelOptions(
            name='orderlist',
            options={'verbose_name': 'Order list', 'verbose_name_plural': 'Order list'},
        ),
        migrations.AlterModelOptions(
            name='repairer',
            options={'verbose_name': 'Repairman', 'verbose_name_plural': 'Repairman'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Type of works', 'verbose_name_plural': 'Type of work'},
        ),
        migrations.AlterModelOptions(
            name='streertbilisi',
            options={'verbose_name': 'Street', 'verbose_name_plural': 'Street'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity_type',
            field=models.CharField(blank=True, choices=[('SV', 'Service'), ('ME', 'Meter'), ('QL', 'Kilogram'), ('TH', 'Thing')], max_length=3, null=True, verbose_name='Measurement'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_city',
            field=models.CharField(blank=True, choices=[('TB', 'Tbilisi'), ('BT', 'Batumi')], default='TB', max_length=2, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_street_app',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='customer_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Company code '),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='customer_phone',
            field=models.CharField(max_length=16, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_status',
            field=models.CharField(blank=True, choices=[('BEG', 'Request received'), ('SND', 'Request sent to the master'), ('RCV', 'Master accepted the request'), ('END', 'Request finished')], default='BEG', max_length=3, null=True, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='text_order',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Description of the problem'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of order'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Order completion date'),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='city',
            field=models.CharField(choices=[('TB', 'Tbilisi'), ('BT', 'Batumi')], default='TB', max_length=2),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/repairer/', verbose_name='Photo:'),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='profile',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='About me:'),
        ),
        migrations.AlterField(
            model_name='repairer',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, choices=[('EL', 'Electrician'), ('PL', 'Plumbing'), ('SP', 'Conditioning'), ('FT', 'Furniture repair/installation'), ('OT', 'Repair of windows and doors'), ('ID', 'Installation of equipment'), ('BL', 'Construction works'), ('CL', 'Cleaning')], max_length=3, null=True, verbose_name='type of work'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Phone')),
                ('telegram', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Telegram')),
                ('city', models.CharField(choices=[('TB', 'Tbilisi'), ('BT', 'Batumi')], default='TB', max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/owner', verbose_name='Photo:')),
                ('rating_sum', models.IntegerField(blank=True, default=0, null=True)),
                ('rating_num', models.IntegerField(blank=True, default=1, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owner',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_city', models.CharField(blank=True, choices=[('TB', 'Tbilisi'), ('BT', 'Batumi')], default='TB', max_length=2, null=True, verbose_name='City')),
                ('address_street_app', models.CharField(blank=True, max_length=150, null=True, verbose_name='Street')),
                ('address_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='House number')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/appartment/', verbose_name='Photo:')),
                ('location_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('location_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('notes', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Note:')),
                ('owner', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsible person for apartment')),
            ],
            options={
                'verbose_name': 'Appartment list',
                'verbose_name_plural': 'Appartment list',
            },
        ),
        migrations.AddField(
            model_name='orderlist',
            name='apartment_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.apartment', verbose_name='Appartment'),
        ),
    ]
