# Generated by Django 4.2 on 2024-03-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0040_alter_invoice_options_alter_orderlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='secret_pk',
        ),
    ]
