# Generated by Django 4.2 on 2024-03-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0041_rename_repairer_userprofile_delete_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
    ]
