# Generated by Django 4.2 on 2024-03-09 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0041_remove_orderlist_secret_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='secret_pk',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
