# Generated by Django 4.2 on 2024-03-09 17:34

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("app_site", "OrderList")
    for row in MyModel.objects.all():
        row.secret_pk = uuid.uuid4()
        row.save(update_fields=["secret_pk"])

class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0042_orderlist_secret_pk'),
    ]


    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        ]
