# Generated by Django 4.2 on 2024-05-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0043_alter_repairer_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='customer_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.userprofile', verbose_name='Client'),
        ),
    ]
