# Generated by Django 4.2 on 2024-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0044_alter_orderlist_secret_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='comment_from_customer',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Description about quality works and services'),
        ),
    ]
