# Generated by Django 4.2 on 2024-04-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0044_orderlist_customer_id_userprofile_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='address_num',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='address_street_app',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='customer_telegram',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='location_longitude',
        ),
    ]
