# Generated by Django 4.2 on 2024-04-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0045_remove_orderlist_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.CharField(blank=True, choices=[('FL', 'Flat'), ('HM', 'Home'), ('OF', 'Office'), ('RS', 'Restaurant'), ('SH', 'Store'), ('OT', 'Other')], default='FL', max_length=2, null=True, verbose_name='Type'),
        ),
    ]
