# Generated by Django 4.2 on 2024-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0047_alter_apartment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, default='images/none.jpg', null=True, upload_to='images/', verbose_name='Photo:'),
        ),
    ]
