# Generated by Django 4.2 on 2024-04-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0048_alter_userprofile_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreerTbilisi',
            new_name='StreetTbilisi',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo:'),
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_feedback', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Feedback')),
                ('mark', models.IntegerField(blank=True, default=0, null=True, verbose_name='Raiting')),
                ('customer_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.userprofile', verbose_name='Client')),
            ],
        ),
    ]
