# Generated by Django 4.2 on 2024-04-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0050_clientfeedback_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfeedback',
            name='customer_id',
        ),
    ]
