# Generated by Django 4.2 on 2024-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0052_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telegram'),
        ),
    ]
