# Generated by Django 4.2 on 2024-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0053_alter_userprofile_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='About me:'),
        ),
    ]
