# Generated by Django 4.2 on 2024-05-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0054_alter_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='location_longitude',
        ),
        migrations.AddField(
            model_name='apartment',
            name='link_location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='GeoPoint'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address_city',
            field=models.CharField(blank=True, choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury')], default='TB', max_length=2, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address_num',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address_street_app',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='Note:'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.userprofile', verbose_name='Responsible person for apartment'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.orderlist', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury')], default='TB', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Telegram'),
        ),
    ]
