# Generated by Django 4.2 on 2024-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0055_remove_apartment_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='About me:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Whatsapp'),
        ),
    ]
