# Generated by Django 4.2 on 2024-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0058_alter_orderlist_apartment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address_city',
            field=models.CharField(blank=True, choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury'), ('RS', 'Rustaveli')], default='TB', max_length=2, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Note:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury'), ('RS', 'Rustaveli')], default='TB', max_length=2),
        ),
    ]
