# Generated by Django 4.2 on 2024-12-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0059_clients_alter_apartment_address_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
