# Generated by Django 4.2 on 2024-12-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0060_rename_clients_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
