# Generated by Django 4.2 on 2024-12-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0061_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfeedback',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
