# Generated by Django 4.2 on 2024-12-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('app_site', '0063_alter_apartment_owner_alter_orderlist_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='owner',
        ),
        migrations.DeleteModel(
            name='StreetTbilisi',
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='apartment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.apartment', verbose_name='Appartment'),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
