# Generated by Django 4.2 on 2024-12-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0064_remove_apartment_owner_delete_streettbilisi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlist',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Type of work', 'verbose_name_plural': 'Type of works'},
        ),
    ]
