# Generated by Django 3.2.4 on 2023-04-23 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RepairerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('s_name', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Электронная почта')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография:')),
                ('active', models.BooleanField(default=False)),
                ('rating_sum', models.IntegerField(default=0)),
                ('rating_num', models.IntegerField(default=0)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='www.citydirectory', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('price', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('text_order', models.CharField(max_length=1500, verbose_name='Описание проблемы')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('customer_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('customer_feedback', models.CharField(max_length=1500, null=True)),
                ('address_street_app', models.CharField(max_length=150, verbose_name='Адрес')),
                ('address_city_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='www.citydirectory', verbose_name='Город')),
                ('repairer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.repairerlist')),
            ],
        ),
    ]
