# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0418\u043c\u044f')),
                ('s_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
            ],
        ),
    ]
