# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u041f\u043e\u0447\u0442\u0430'),
        ),
    ]
