# Generated by Django 4.2 on 2023-05-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0011_remove_orderlist_customer_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_area',
            field=models.CharField(blank=True, choices=[('DB', 'Дидубе'), ('KR', 'Крцаниси'), ('ND', 'Надзаладеви'), ('GR', 'Грмагеле'), ('ZG', 'Згвис'), ('GL', 'Глдани'), ('DI', 'Дигоми'), ('DD', 'Диди Дигоми'), ('IS', 'Исани'), ('SM', 'Самгори')], default='', max_length=3, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_city',
            field=models.CharField(blank=True, choices=[('TB', 'Тбилиси'), ('BT', 'Батуми'), ('RS', 'Рустави')], default='TB', max_length=2, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address_street_app',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость работ'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='repairer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.repairerlist', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='text_order',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='repairerlist',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='repairerlist',
            name='rating_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='repairerlist',
            name='rating_sum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
