# Generated by Django 4.2 on 2023-05-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0012_ordercategory_alter_orderlist_address_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='address_area',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='work_type',
            field=models.CharField(blank=True, choices=[('EL', 'Электрика'), ('PL', 'Сантехника'), ('SP', 'Кондиционирование'), ('FT', 'Ремонт/сборка мебели'), ('OT', 'Ремонт окон, дверей')], default='', max_length=3, null=True, verbose_name='Вид работ'),
        ),
    ]
