# Generated by Django 4.2 on 2023-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0015_alter_orderlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость работ'),
        ),
    ]
