# Generated by Django 4.2 on 2023-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0017_invoice_service_delete_ordercategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='Дата счета'),
        ),
    ]
