# Generated by Django 4.2 on 2023-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0021_alter_orderlist_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='customer_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Код организации'),
        ),
    ]
