# Generated by Django 4.2 on 2023-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0024_alter_repairerlist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='work_type',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_status',
            field=models.CharField(blank=True, choices=[('BEG', 'Заявка получен'), ('SND', 'Направлена мастеру'), ('END', 'Заявка выполнена'), ('CNL', 'Заявка отменена')], default='BEG', max_length=3, null=True, verbose_name='Статус заказа'),
        ),
    ]
