# Generated by Django 4.2 on 2023-11-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0037_alter_streertbilisi_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='price',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_status',
            field=models.CharField(blank=True, choices=[('BEG', 'Заявка получена'), ('SND', 'Направлена мастеру'), ('RCV', 'Мастеру принял заявку'), ('END', 'Заявка выполнена')], default='BEG', max_length=3, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='repairerlist',
            name='rating_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
