# Generated by Django 4.2 on 2023-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fggg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(max_length=255)),
                ('b', models.TextField(max_length=255)),
            ],
        ),
    ]
