# Generated by Django 4.2 on 2024-12-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_userprofile_rating_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Name')),
                ('type', models.CharField(blank=True, choices=[('FL', 'Flat'), ('HM', 'Home'), ('OF', 'Office'), ('RS', 'Restaurant'), ('SH', 'Store'), ('OT', 'Other')], default='FL', max_length=2, null=True, verbose_name='Type')),
                ('address_city', models.CharField(blank=True, choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury'), ('RS', 'Rustaveli')], default='TB', max_length=2, null=True, verbose_name='City')),
                ('address_street_app', models.CharField(blank=True, default=' ', max_length=150, null=True, verbose_name='Street')),
                ('address_num', models.CharField(blank=True, default=' ', max_length=10, null=True, verbose_name='House number')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/appartment/', verbose_name='Photo:')),
                ('notes', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Note:')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.userprofile', verbose_name='Responsible person for apartment')),
            ],
            options={
                'verbose_name': 'Appartment list',
                'verbose_name_plural': 'Appartment list',
            },
        ),
    ]
