# Generated by Django 4.2 on 2025-11-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_remove_apartment_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id_apartments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apartments.apartment', verbose_name='Id apartments')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/appartment/', verbose_name='Photo:')),
            ],
            options={
                'verbose_name': 'Appartment_photo',
                'verbose_name_plural': 'Appartments_photo',
            },
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='foto',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address_city',
            field=models.CharField(blank=True, choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury'), ('RS', 'Rustavi'), ('OT', 'Other')], default='TB', max_length=2, null=True, verbose_name='City'),
        ),
    ]
