# Generated by Django 4.2.18 on 2025-11-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_alter_apartment_address_city_apartment_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment_photo',
            new_name='ApartmentPhoto',
        ),
    ]
