# Generated by Django 4.2.18 on 2025-11-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_rename_apartment_photo_apartmentphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentphoto',
            name='id',
        ),
        migrations.AlterField(
            model_name='apartmentphoto',
            name='id_apartments',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apartments.apartment', verbose_name='Id apartments'),
        ),
    ]
