# Generated by Django 4.2 on 2024-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
    ]
