# Generated by Django 4.2 on 2024-12-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_masterprofile_user_masterprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Name'),
        ),
    ]
