# Generated by Django 4.2.18 on 2025-11-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_masterprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='city',
            field=models.CharField(choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury'), ('RS', 'Rustavi'), ('OT', 'Other')], default='TB', max_length=2),
        ),
    ]
