# Generated by Django 4.2 on 2024-12-20 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_site', '0062_remove_clientfeedback_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone')),
                ('telegram', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=16, null=True, verbose_name='Whatsapp')),
                ('city', models.CharField(choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury'), ('RS', 'Rustaveli')], default='TB', max_length=2)),
                ('profile', models.CharField(blank=True, max_length=1500, null=True, verbose_name='About me:')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo:')),
                ('rating_sum', models.IntegerField(blank=True, default=0, null=True)),
                ('rating_num', models.IntegerField(blank=True, default=1, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_feedback', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Feedback')),
                ('mark', models.IntegerField(blank=True, default=0, null=True, verbose_name='Raiting')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_site.orderlist', verbose_name='Order')),
            ],
        ),
    ]
