# Generated by Django 4.2 on 2024-12-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_num',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_sum',
        ),
    ]
