# Generated by Django 4.2 on 2024-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_userprofile_rating_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating_num',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_sum',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
