# Generated by Django 4.2 on 2025-11-27 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_userprofile_qrcode_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_num',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_sum',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('TB', 'Tbilisi'), ('BT', 'Batumi'), ('GD', 'Gudaury'), ('RS', 'Rustavi'), ('OT', 'Other')], default='TB', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qrcode_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
